### ISSUE TITLE
Some return types are not public

### ISSUE THREAD

**Issue by mullerch** [maltegrosse/go-modemmanager#7]
Some public functions, such as [Modem3gpp.Scan()](https://github.com/maltegrosse/go-modemmanager/blob/8420f1b68d0403d9cff06ee1e4ef319e55a7c8fb/Modem3gpp.go#L51) return private types ([network3Gpp](https://github.com/maltegrosse/go-modemmanager/blob/8420f1b68d0403d9cff06ee1e4ef319e55a7c8fb/Modem3gpp.go#L148)). Those types have no functions that can ingest them to return useful public types. Those functions seem therefore useless.

I don't see a reason for the following types (non-exhaustive) to be made private:

- network3Gpp
- networkScanResult
- rawPcoData
- port
- bearerIpConfig
- bearerStats

Is this visibility intentional? If yes, how are we supposed to use the output of those functions?

**Comment by maltegrosse** [comment]
Hi @mullerch 
Its quite a long time ago I did this implementation, but I try my best to explain it (as far as I remember)

You can get the values as following: (ignored errors by _)

```
mmgr,_ := modemmanager.NewModemManager()
modems, _ := mmgr.GetModems()
for _,m :=range modems{
	ports, _ := m.GetPorts()
	for _, p := range ports{
		fmt.Println(p.PortName)
	}
	g, _ := m.Get3gpp()
	g.RequestScan()
	sc,_ := g.Scan()
	for _,scans := range sc{
		fmt.Println(scans.Mcc)
	}
	res, _ := g.GetScanResults()
	
	for _, net := range res.Networks{
		fmt.Println(net.Mcc)
	}
	rawPco ,_ := g.GetPco()
	fmt.Println(rawPco)
	
	bearer, _ :=g.GetInitialEpsBearer()
	ip, _ := bearer.GetIp4Config()
	fmt.Println(ip.Address)

	stats,_ := bearer.GetStats()
	fmt.Println(stats)
	
}
```

Most of the structs are just helper structs,in order to access the raw dbus values in a more convenient way.

Getting the different values can caus multiple errors on dbus side + parsing etc. The functions are created to make the user aware of these errors.  In my opinion there is no need to make the structs public, as their properties are public and functions to access them exist. (and the users can not do anything with these structs on their own...)

Let me know if I am wrong and any improvements/PRs are welcome

Additionally, a basic example exist here: https://github.com/maltegrosse/go-modemmanager/blob/master/examples/test_run.go

**Comment by mullerch** [comment]
Thanks for your quick answer. 

With private visibility of the type, the library user cannot:

1. Declare a variable of that type
2. Use the type as parameter / return type of a function
3. Instantiate the type

1 & 2 impose design constraints to the user's code, which is weird (e.g. you cannot create a wrapper function without abstracting the type). I don't see any reason why one may need 3.

I suggest making those types public so that there are no such constraints (I can PR that).

**Comment by maltegrosse** [comment]
@mullerch , thanks for explanation.
2. is a valid point - especially if you wanna use that types in your further application logic.

Sure, more than welcome to do a PR. But please consider all structs (I think 19)

Thank you.

PS thanks (wifx) for the network manager golang library - was my inspiration for getting started with go and modem manager...

**Comment by mullerch** [comment]
Credits for gonetworkmanager have to go to https://github.com/BellerophonMobile/ who initially made that library
